### ISSUE TITLE
Create interface for retrieval of similar annotations

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#59]
# Description

For the CBIR feature, in the annotation details, allow the user to retrieve similar annotations in the same project.

# Task

- [x] Implement the indexing of new annotations automatically
- [x] Implement a button in the annotation details to allow the search of similar annotations
- [x] Implement the view of the search results in a pop up
- [x] Implementation of the logic behind the button and the retrieval
- [x] Implementation of the deletion when deleting an annotation
- [x] Add a suggested term to add based on the other annotations' terms
