### ISSUE TITLE
Create unit tests for `annotations` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#69]
# Description

Create tests for admin components located in `src/components/annotations` directory.

# Task

- [ ] Create unit tests for `AnnotationCommentsModal.vue`
- [ ] Create unit tests for `AnnotationDetails.vue`
- [ ] Create unit tests for `AnnotationLinksPreview.vue`
- [ ] Create unit tests for `AnnotationPreview.vue`
- [ ] Create unit tests for `ListAnnotations.vue`
- [ ] Create unit tests for `ListAnnotationsBy.vue`
- [ ] Create unit tests for `SimilarAnnotation.vue`
