### ISSUE TITLE
Create unit tests for `form` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#73]
# Description

Create tests for admin components located in `src/components/form` directory.

# Task

- [ ] Create unit tests for `CytomineDatepicker.vue`
- [ ] Create unit tests for `CytomineMultiselect.vue`
- [ ] Create unit tests for `CytomineQuillEditor.vue`
- [ ] Create unit tests for `CytomineSlider.vue`
