### ISSUE TITLE
Create unit tests for `image-group` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#74]
# Description

Create tests for admin components located in `src/components/image-group` directory.

# Task

- [ ] Create unit tests for `AddImageGroupModal.vue`
- [ ] Create unit tests for `AddToImageGroupModal.vue`
- [ ] Create unit tests for `ImageGroupDetails.vue`
- [ ] Create unit tests for `ImageGroupPreview.vue`
- [ ] Create unit tests for `ListImageGroups.vue`
- [ ] Create unit tests for `OpenImageGroupButton.vue`
- [ ] Create unit tests for `SimpleAddToImageGroupModal.vue`
