### ISSUE TITLE
Create unit tests for `navbar` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#76]
# Description

Create tests for admin components located in `src/components/navbar` directory.

# Task

- [ ] Create unit tests for `AboutCytomineModal.vue`
- [ ] Create unit tests for `CytomineNavbar.vue`
- [ ] Create unit tests for `HotkeysModal.vue`
- [ ] Create unit tests for `NavbarDropdown.vue`
- [ ] Create unit tests for `NavigationTree.vue`
