### ISSUE TITLE
Create unit tests for `ontology` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#77]
# Description

Create tests for admin components located in `src/components/ontology` directory.

# Task

- [ ] Create unit tests for `AddOntologyModal.vue`
- [ ] Create unit tests for `CytomineTerm.vue`
- [ ] Create unit tests for `ListOntologies.vue`
- [ ] Create unit tests for `OntologyDetails.vue`
- [ ] Create unit tests for `OntologyTree.vue`
- [ ] Create unit tests for `OntologyTreeMultiselect.vue`
- [ ] Create unit tests for `TermModal.vue`
