### ISSUE TITLE
Create unit tests for `project` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#78]
# Description

Create tests for admin components located in `src/components/project` directory.

# Task

- [ ] Create unit tests for `AddProjectModal.vue`
- [ ] Create unit tests for `CytomineProject.vue`
- [ ] Create unit tests for `ListProjects.vue`
- [ ] Create unit tests for `ProjectActions.vue`
- [ ] Create unit tests for `ProjectActivity.vue`
- [ ] Create unit tests for `ProjectConfiguration.vue`
- [ ] Create unit tests for `ProjectConnectionDetails.vue`
- [ ] Create unit tests for `ProjectDetails.vue`
- [ ] Create unit tests for `ProjectHome.vue`
- [ ] Create unit tests for `ProjectInformation.vue`
- [ ] Create unit tests for `ProjectSidebar.vue`
