### ISSUE TITLE
Create unit tests for `storage` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#81]
# Description

Create tests for admin components located in `src/components/storage` directory.

# Task

- [ ] Create unit tests for `CytomineStorage.vue`
- [ ] Create unit tests for `ProfileStatus.vue`
- [ ] Create unit tests for `UploadedFileDetails.vue`
- [ ] Create unit tests for `UploadedFileStatus.vue`
