### ISSUE TITLE
Create unit tests for `tag` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#82]
# Description

Create tests for admin components located in `src/components/tag` directory.

# Task

- [ ] Create unit tests for `AddTagDomainAssociationModal.vue`
- [ ] Create unit tests for `CytomineTags.vue`
- [ ] Create unit tests for `TagModal.vue`
