### ISSUE TITLE
Create unit tests for `track` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#83]
# Description

Create tests for track components located in `src/components/track` directory.

# Task

- [ ] Create unit tests for `CytomineTrack.vue`
- [ ] Create unit tests for `TrackModal.vue`
- [ ] Create unit tests for `TrackTree.vue`
- [ ] Create unit tests for `TrackTreeMultiselect.vue`
