### ISSUE TITLE
Create unit tests for `user` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#84]
# Description

Create tests for user components located in `src/components/user` directory.

# Task

- [ ] Create unit tests for `Account.vue`
- [ ] Create unit tests for `ListUsernames.vue`
- [ ] Create unit tests for `Login.vue`
- [ ] Create unit tests for `Register.vue`
- [ ] Create unit tests for `UserActivity.vue`
- [ ] Create unit tests for `UserTaginput.vue`
- [ ] Create unit tests for `Username.vue`
