### ISSUE TITLE
Create unit tests for `utils` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#85]
# Description

Create tests for utils components located in `src/components/utils` directory.

# Task

- [x] Create unit tests for `ActivityLogs.vue`
- [x] Create unit tests for `ActivityLogsItem.vue`
- [x] Create unit tests for `BooleanItem.vue`
- [x] Create unit tests for `CytomineModal.vue`
- [x] Create unit tests for `CytomineModalCard.vue`
- [x] Create unit tests for `CytomineTask.vue`
- [x] Create unit tests for `DomainTagInput.vue`
- [x] Create unit tests for `RenameModal.vue`
