### ISSUE TITLE
Create unit tests for `viewer` components

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-Web-UI#86]
# Description

Create tests for viewer components located in `src/components/viewer` directory.

# Task

- [ ] Create unit tests for `AnnotationDetailsContainer.vue`
- [ ] Create unit tests for `AnnotationLayer.vue`
- [ ] Create unit tests for `AnnotationProfileProjectionTable.vue`
- [ ] Create unit tests for `AnnotationsContainer.vue`
- [ ] Create unit tests for `AnnotationsList.vue`
- [ ] Create unit tests for `ChannelName.vue`
- [ ] Create unit tests for `CytomineImage.vue`
- [ ] Create unit tests for `CytomineViewer.vue`
- [ ] Create unit tests for `DrawTools.vue`
- [ ] Create unit tests for `ImageControls.vue`
- [ ] Create unit tests for `ImageControlsShiftButtons.vue`
- [ ] Create unit tests for `ImageSelector.vue`
- [ ] Create unit tests for `ProfileModal.vue`
- [ ] Create unit tests for `RotationSelector.vue`
- [ ] Create unit tests for `ScaleLine.vue`
- [ ] Create unit tests for directory `interactions`
  - [ ] Create unit tests for `AnnotationLinkSelector.vue`
  - [ ] Create unit tests for `DrawInteraction.vue`
  - [ ] Create unit tests for `ModifyInteraction.vue`
  - [ ] Create unit tests for `PasteAnnotationWithLinkModal.vue`
  - [ ] Create unit tests for `SelectInteraction.vue`
  - [ ] Create unit tests for `ToggleScaleLine.vue`
- [ ] Create unit tests for directory `panels`
  - [ ] Create unit tests for `ColorManipulation.vue`
  - [ ] Create unit tests for `DigitalZoom.vue`
  - [ ] Create unit tests for `FollowPanel.vue`
  - [ ] Create unit tests for `InformationPanel.vue`
  - [ ] Create unit tests for `LayersPanel.vue`
  - [ ] Create unit tests for `LinkPanel.vue`
  - [ ] Create unit tests for `MetadataPanel.vue`
  - [ ] Create unit tests for `OntologyPanel.vue`
  - [ ] Create unit tests for `PropertiesPanel.vue`
  - [ ] Create unit tests for `ReviewPanel.vue`
